import Head from 'next/head'
import { Inter, Amiri } from '@next/font/google'
import Hero from '../components/Hero'
import Header from '../components/Header'
import PlaceList from '../components/PlaceList'
import About from '../components/About'

const inter = Inter({ subsets: ['latin'], })


export default function Home() {
  

  return (
    <>
      <Head>
        <title>Explore Daga</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className} bg-slate-900 text-white scroll-smooth`}> 
          <Header /> 
          <Hero/>
          <div className='flex flex-col justify-center items-center w-full mt-16'>
            <About />
            <PlaceList />
          </div>  
          
      </main>
    </>
  )
}
