import React from 'react'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import Image from 'next/image'
import { Strom_1, Strom_2 } from './assets'

const inter = Inter({ subsets: ['latin'], })

const StromPage = () => {
  return (
    <>
      <Head>
        <title>Explore Daga - Strom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${inter.className} bg-slate-900 text-white scroll-smooth`}>
        <div className="bg-[url('/images/Strom_tn.png')] h-[500px] w-full bg-no-repeat bg-cover bg-center backdrop-brightness-50 backdrop-blur-lg flex items-end">
          <div>
            <h1 className='text-[32px] lg:text-[68px] w-full bg-cyan-900 font-bold p-4 shadow-lg'>Glória à cidade de pedra</h1>
          </div>  
        </div>
        <div className='flex flex-col items-center w-full '>
          <h1 className='text-[32px] lg:text-[56px] text-center font-bold pt-6'>História</h1>
          <article className='grid grid-flow-row md:grid-flow-col auto-cols-auto m-8 gap-8'>
          <Image
            src={Strom_2}
            alt="Antiga pintura do reino de Strom"
            className='w-auto'
          />
          <p className='text-justify'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla maximus magna id mauris hendrerit maximus. Vivamus eget dolor ac felis bibendum posuere tempus eu erat. Quisque efficitur enim in turpis blandit facilisis. Vivamus aliquet tempor tellus, non dignissim odio maximus vel. Praesent posuere, nisl a viverra viverra, elit ante condimentum felis, a finibus magna dolor placerat nibh. Etiam tempor aliquam imperdiet. Phasellus elementum diam vel pharetra porttitor. Vestibulum malesuada mauris ac congue iaculis. Suspendisse vitae mi volutpat, porttitor justo ac, ullamcorper nunc. Fusce euismod purus vel diam auctor mollis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In facilisis ullamcorper tortor ut porttitor. Curabitur ac felis lorem. Maecenas risus felis, congue non lacus nec, tincidunt lobortis turpis.

            Phasellus et pharetra turpis. Morbi posuere tempus augue eu pretium. Nunc malesuada lectus eget suscipit eleifend. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus et leo fringilla, tempor quam ac, sodales tortor. Morbi volutpat vitae sem non pretium. Cras tempus suscipit nisl, vitae dictum ex sagittis ac. Praesent vel molestie dolor, eget dignissim lacus. Nullam gravida velit pulvinar, dignissim sem vitae, facilisis velit. Donec quis nulla egestas, feugiat dolor vel, viverra tortor. In non dapibus quam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus nec interdum dolor. Nullam sit amet tortor pharetra nisi elementum pretium. Nunc vel lacus vitae neque iaculis egestas at eu sapien. Integer nec enim eget lorem tempus euismod.
          </p>
          </article>
        </div>
      </main>
    </>
  )
}

export default StromPage