import React from 'react'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Strom } from '../../../components/PlaceList/assets'

const inter = Inter({ subsets: ['latin'], })

const StromPage = () => {
  return (
    <>
      <Head>
        <title>Explore Daga - Strom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${inter.className} bg-slate-900 text-white scroll-smooth`}>
        <div className="bg-[url('/images/Strom_tn.png')] h-[500px] w-full bg-no-repeat bg-cover bg-center backdrop-brightness-50 backdrop-blur-sm flex justify-center items-center">
          <div>
            <h1 className='text-[68px]'>Glória à cidade de pedra</h1>
          </div>  
        </div>
      </main>
    </>
  )
}

export default StromPage